# Generated by Django 5.0.7 on 2024-09-04 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='safepay_id',
            new_name='stripe_id',
        ),
    ]
