# Generated by Django 5.0.7 on 2024-09-08 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_init_email_customer_init_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='init_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='init_email_confirmed',
        ),
    ]
