# Generated by Django 5.0.7 on 2024-09-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_subscriptionprice_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={'ordering': ['order', 'featured', '-updated']},
        ),
        migrations.AlterField(
            model_name='subscriptionprice',
            name='order',
            field=models.IntegerField(default=-1, help_text='Display Order On the pricing page'),
        ),
    ]
